version: '3.1'
services:
  web:
    build: .
    image: tinder
    ports:
     - "3000:3000"
    command: pm2-docker process.yml
    env_file: .env
    restart: always
    volumes:
      - "./upload:/upload"
